// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vesselMotionAggregator/proto/v1/vessel_motion_aggregator_api_v1.proto

package vesselMotionAggregator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type VMEstimateRequest struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Latitude             []float32 `protobuf:"fixed32,2,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            []float32 `protobuf:"fixed32,3,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Heading              []float32 `protobuf:"fixed32,4,rep,packed,name=heading,proto3" json:"heading,omitempty"`
	PropPitch            []float32 `protobuf:"fixed32,5,rep,packed,name=prop_pitch,json=propPitch,proto3" json:"prop_pitch,omitempty"`
	MotorSpeed           []float32 `protobuf:"fixed32,6,rep,packed,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	SOG                  []float32 `protobuf:"fixed32,7,rep,packed,name=SOG,proto3" json:"SOG,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *VMEstimateRequest) Reset()         { *m = VMEstimateRequest{} }
func (m *VMEstimateRequest) String() string { return proto.CompactTextString(m) }
func (*VMEstimateRequest) ProtoMessage()    {}
func (*VMEstimateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_578fcf2461e7b08c, []int{0}
}

func (m *VMEstimateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMEstimateRequest.Unmarshal(m, b)
}
func (m *VMEstimateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMEstimateRequest.Marshal(b, m, deterministic)
}
func (m *VMEstimateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMEstimateRequest.Merge(m, src)
}
func (m *VMEstimateRequest) XXX_Size() int {
	return xxx_messageInfo_VMEstimateRequest.Size(m)
}
func (m *VMEstimateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_VMEstimateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_VMEstimateRequest proto.InternalMessageInfo

func (m *VMEstimateRequest) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *VMEstimateRequest) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *VMEstimateRequest) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *VMEstimateRequest) GetHeading() []float32 {
	if m != nil {
		return m.Heading
	}
	return nil
}

func (m *VMEstimateRequest) GetPropPitch() []float32 {
	if m != nil {
		return m.PropPitch
	}
	return nil
}

func (m *VMEstimateRequest) GetMotorSpeed() []float32 {
	if m != nil {
		return m.MotorSpeed
	}
	return nil
}

func (m *VMEstimateRequest) GetSOG() []float32 {
	if m != nil {
		return m.SOG
	}
	return nil
}

type VMEstimateResponse struct {
	UnixTime              []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	AccelerationEstimateX []float64 `protobuf:"fixed64,2,rep,packed,name=acceleration_estimate_x,json=accelerationEstimateX,proto3" json:"acceleration_estimate_x,omitempty"`
	AccelerationEstimateY []float64 `protobuf:"fixed64,3,rep,packed,name=acceleration_estimate_y,json=accelerationEstimateY,proto3" json:"acceleration_estimate_y,omitempty"`
	AccelerationEstimateZ []float64 `protobuf:"fixed64,4,rep,packed,name=acceleration_estimate_z,json=accelerationEstimateZ,proto3" json:"acceleration_estimate_z,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *VMEstimateResponse) Reset()         { *m = VMEstimateResponse{} }
func (m *VMEstimateResponse) String() string { return proto.CompactTextString(m) }
func (*VMEstimateResponse) ProtoMessage()    {}
func (*VMEstimateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_578fcf2461e7b08c, []int{1}
}

func (m *VMEstimateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_VMEstimateResponse.Unmarshal(m, b)
}
func (m *VMEstimateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_VMEstimateResponse.Marshal(b, m, deterministic)
}
func (m *VMEstimateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_VMEstimateResponse.Merge(m, src)
}
func (m *VMEstimateResponse) XXX_Size() int {
	return xxx_messageInfo_VMEstimateResponse.Size(m)
}
func (m *VMEstimateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_VMEstimateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_VMEstimateResponse proto.InternalMessageInfo

func (m *VMEstimateResponse) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *VMEstimateResponse) GetAccelerationEstimateX() []float64 {
	if m != nil {
		return m.AccelerationEstimateX
	}
	return nil
}

func (m *VMEstimateResponse) GetAccelerationEstimateY() []float64 {
	if m != nil {
		return m.AccelerationEstimateY
	}
	return nil
}

func (m *VMEstimateResponse) GetAccelerationEstimateZ() []float64 {
	if m != nil {
		return m.AccelerationEstimateZ
	}
	return nil
}

func init() {
	proto.RegisterType((*VMEstimateRequest)(nil), "vesselMotionAggregator.v1.VMEstimateRequest")
	proto.RegisterType((*VMEstimateResponse)(nil), "vesselMotionAggregator.v1.VMEstimateResponse")
}

func init() {
	proto.RegisterFile("vesselMotionAggregator/proto/v1/vessel_motion_aggregator_api_v1.proto", fileDescriptor_578fcf2461e7b08c)
}

var fileDescriptor_578fcf2461e7b08c = []byte{
	// 351 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x52, 0xcd, 0x4a, 0xeb, 0x40,
	0x14, 0x26, 0xcd, 0xbd, 0xfd, 0x39, 0x77, 0xd3, 0x3b, 0x28, 0xc6, 0xaa, 0x58, 0xba, 0xea, 0x42,
	0x13, 0x62, 0xc1, 0x8d, 0x2b, 0x85, 0xe2, 0xaa, 0x28, 0xa9, 0x14, 0xed, 0x26, 0x8c, 0xe9, 0x21,
	0x1d, 0x48, 0x32, 0x63, 0x66, 0x1a, 0xaa, 0x2f, 0xe0, 0x1b, 0x0a, 0xbe, 0x8d, 0xcc, 0xc4, 0xd6,
	0x82, 0x8d, 0xb8, 0x9b, 0xf3, 0xfd, 0x0c, 0x7c, 0xdf, 0x39, 0x30, 0x2c, 0x50, 0x4a, 0x4c, 0x46,
	0x5c, 0x31, 0x9e, 0x5d, 0xc6, 0x71, 0x8e, 0x31, 0x55, 0x3c, 0xf7, 0x44, 0xce, 0x15, 0xf7, 0x0a,
	0xdf, 0x2b, 0xf9, 0x30, 0x35, 0x82, 0x90, 0xae, 0x15, 0x21, 0x15, 0x2c, 0x2c, 0x7c, 0xd7, 0x08,
	0xc9, 0xfe, 0xf6, 0x6f, 0xdc, 0xc2, 0xef, 0xbd, 0x59, 0xf0, 0x7f, 0x32, 0x1a, 0x4a, 0xc5, 0x52,
	0xaa, 0x30, 0xc0, 0xa7, 0x05, 0x4a, 0x45, 0x0e, 0xa0, 0xb5, 0xc8, 0xd8, 0x32, 0x54, 0x2c, 0x45,
	0xc7, 0xea, 0xda, 0x7d, 0x2b, 0x68, 0x6a, 0xe0, 0x8e, 0xa5, 0x48, 0x3a, 0xd0, 0x4c, 0xa8, 0x62,
	0x6a, 0x31, 0x43, 0xa7, 0xd6, 0xb5, 0xfb, 0xb5, 0x60, 0x3d, 0x93, 0x43, 0x68, 0x25, 0x3c, 0x8b,
	0x4b, 0xd2, 0x36, 0xe4, 0x17, 0x40, 0x1c, 0x68, 0xcc, 0x91, 0xce, 0x58, 0x16, 0x3b, 0x7f, 0x0c,
	0xb7, 0x1a, 0xc9, 0x11, 0x80, 0xc8, 0xb9, 0x08, 0x05, 0x53, 0xd1, 0xdc, 0xf9, 0x5b, 0x1a, 0x35,
	0x72, 0xab, 0x01, 0x72, 0x0c, 0xff, 0x52, 0xae, 0x63, 0x49, 0x81, 0x38, 0x73, 0xea, 0x86, 0x07,
	0x03, 0x8d, 0x35, 0x42, 0xda, 0x60, 0x8f, 0x6f, 0xae, 0x9d, 0x86, 0x21, 0xf4, 0xb3, 0xf7, 0x6e,
	0x01, 0xd9, 0x0c, 0x26, 0x05, 0xcf, 0x24, 0xfe, 0x9c, 0xec, 0x1c, 0xf6, 0x68, 0x14, 0x61, 0x82,
	0x39, 0x35, 0x7d, 0xe2, 0xa7, 0x3b, 0x5c, 0x9a, 0xa0, 0x56, 0xb0, 0xbb, 0x49, 0xaf, 0xfe, 0xbe,
	0xaf, 0xf6, 0x3d, 0x9b, 0x0e, 0x2a, 0x7c, 0x0f, 0xd5, 0xbe, 0x17, 0xd3, 0x4f, 0x85, 0x6f, 0x7a,
	0xf6, 0x6a, 0x41, 0x5b, 0x67, 0x33, 0xe3, 0x18, 0xf3, 0x82, 0x45, 0x48, 0x24, 0xec, 0xac, 0x14,
	0x93, 0x8d, 0x75, 0x93, 0x13, 0xb7, 0x72, 0xfb, 0xee, 0xb7, 0xcd, 0x77, 0x4e, 0x7f, 0xa9, 0x2e,
	0xeb, 0xbc, 0x1a, 0x4c, 0xfd, 0x8a, 0x13, 0x2d, 0x7c, 0xef, 0x62, 0x3b, 0xf5, 0x58, 0x37, 0x57,
	0x39, 0xf8, 0x08, 0x00, 0x00, 0xff, 0xff, 0xf0, 0xd8, 0x26, 0xf7, 0xde, 0x02, 0x00, 0x00,
}
