// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package vesselMotionAggregator

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VMEsimateServiceClient is the client API for VMEsimateService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VMEsimateServiceClient interface {
	EstimateVesselMotion(ctx context.Context, in *VMEstimateRequest, opts ...grpc.CallOption) (*VMEstimateResponse, error)
}

type vMEsimateServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVMEsimateServiceClient(cc grpc.ClientConnInterface) VMEsimateServiceClient {
	return &vMEsimateServiceClient{cc}
}

func (c *vMEsimateServiceClient) EstimateVesselMotion(ctx context.Context, in *VMEstimateRequest, opts ...grpc.CallOption) (*VMEstimateResponse, error) {
	out := new(VMEstimateResponse)
	err := c.cc.Invoke(ctx, "/vesselMotionAggregator.v1.VMEsimateService/EstimateVesselMotion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VMEsimateServiceServer is the server API for VMEsimateService service.
// All implementations must embed UnimplementedVMEsimateServiceServer
// for forward compatibility
type VMEsimateServiceServer interface {
	EstimateVesselMotion(context.Context, *VMEstimateRequest) (*VMEstimateResponse, error)
	mustEmbedUnimplementedVMEsimateServiceServer()
}

// UnimplementedVMEsimateServiceServer must be embedded to have forward compatible implementations.
type UnimplementedVMEsimateServiceServer struct {
}

func (UnimplementedVMEsimateServiceServer) EstimateVesselMotion(context.Context, *VMEstimateRequest) (*VMEstimateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EstimateVesselMotion not implemented")
}
func (UnimplementedVMEsimateServiceServer) mustEmbedUnimplementedVMEsimateServiceServer() {}

// UnsafeVMEsimateServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VMEsimateServiceServer will
// result in compilation errors.
type UnsafeVMEsimateServiceServer interface {
	mustEmbedUnimplementedVMEsimateServiceServer()
}

func RegisterVMEsimateServiceServer(s grpc.ServiceRegistrar, srv VMEsimateServiceServer) {
	s.RegisterService(&VMEsimateService_ServiceDesc, srv)
}

func _VMEsimateService_EstimateVesselMotion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VMEstimateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VMEsimateServiceServer).EstimateVesselMotion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/vesselMotionAggregator.v1.VMEsimateService/EstimateVesselMotion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VMEsimateServiceServer).EstimateVesselMotion(ctx, req.(*VMEstimateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VMEsimateService_ServiceDesc is the grpc.ServiceDesc for VMEsimateService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VMEsimateService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "vesselMotionAggregator.v1.VMEsimateService",
	HandlerType: (*VMEsimateServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "EstimateVesselMotion",
			Handler:    _VMEsimateService_EstimateVesselMotion_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "vesselMotionAggregator/proto/v1/vessel_motion_aggregator_api_v1.proto",
}
