// Code generated by protoc-gen-go. DO NOT EDIT.
// source: comfortService/proto/v1/comfort_service_api_v1.proto

package comfortService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HabitibilityRating int32

const (
	HabitibilityRating_UNKNOWN_RATING          HabitibilityRating = 0
	HabitibilityRating_NOT_UNCOMFORTABLE       HabitibilityRating = 1
	HabitibilityRating_SLIGHTLY_UNCOMFORTABLE  HabitibilityRating = 2
	HabitibilityRating_FAIRLY_UNCOMFORTABLE    HabitibilityRating = 3
	HabitibilityRating_UNCOMFORTABLE           HabitibilityRating = 4
	HabitibilityRating_VERY_UNCOMFORTABLE      HabitibilityRating = 5
	HabitibilityRating_EXTREMELY_UNCOMFORTABLE HabitibilityRating = 6
)

var HabitibilityRating_name = map[int32]string{
	0: "UNKNOWN_RATING",
	1: "NOT_UNCOMFORTABLE",
	2: "SLIGHTLY_UNCOMFORTABLE",
	3: "FAIRLY_UNCOMFORTABLE",
	4: "UNCOMFORTABLE",
	5: "VERY_UNCOMFORTABLE",
	6: "EXTREMELY_UNCOMFORTABLE",
}

var HabitibilityRating_value = map[string]int32{
	"UNKNOWN_RATING":          0,
	"NOT_UNCOMFORTABLE":       1,
	"SLIGHTLY_UNCOMFORTABLE":  2,
	"FAIRLY_UNCOMFORTABLE":    3,
	"UNCOMFORTABLE":           4,
	"VERY_UNCOMFORTABLE":      5,
	"EXTREMELY_UNCOMFORTABLE": 6,
}

func (x HabitibilityRating) String() string {
	return proto.EnumName(HabitibilityRating_name, int32(x))
}

func (HabitibilityRating) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8c2e8f0330418358, []int{0}
}

type ComfortRequest struct {
	UnixTime                []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	HumanWeightedVibrationX []float64 `protobuf:"fixed64,2,rep,packed,name=human_weighted_vibration_x,json=humanWeightedVibrationX,proto3" json:"human_weighted_vibration_x,omitempty"`
	HumanWeightedVibrationY []float64 `protobuf:"fixed64,3,rep,packed,name=human_weighted_vibration_y,json=humanWeightedVibrationY,proto3" json:"human_weighted_vibration_y,omitempty"`
	HumanWeightedVibrationZ []float64 `protobuf:"fixed64,4,rep,packed,name=human_weighted_vibration_z,json=humanWeightedVibrationZ,proto3" json:"human_weighted_vibration_z,omitempty"`
	XXX_NoUnkeyedLiteral    struct{}  `json:"-"`
	XXX_unrecognized        []byte    `json:"-"`
	XXX_sizecache           int32     `json:"-"`
}

func (m *ComfortRequest) Reset()         { *m = ComfortRequest{} }
func (m *ComfortRequest) String() string { return proto.CompactTextString(m) }
func (*ComfortRequest) ProtoMessage()    {}
func (*ComfortRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2e8f0330418358, []int{0}
}

func (m *ComfortRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComfortRequest.Unmarshal(m, b)
}
func (m *ComfortRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComfortRequest.Marshal(b, m, deterministic)
}
func (m *ComfortRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComfortRequest.Merge(m, src)
}
func (m *ComfortRequest) XXX_Size() int {
	return xxx_messageInfo_ComfortRequest.Size(m)
}
func (m *ComfortRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ComfortRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ComfortRequest proto.InternalMessageInfo

func (m *ComfortRequest) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *ComfortRequest) GetHumanWeightedVibrationX() []float64 {
	if m != nil {
		return m.HumanWeightedVibrationX
	}
	return nil
}

func (m *ComfortRequest) GetHumanWeightedVibrationY() []float64 {
	if m != nil {
		return m.HumanWeightedVibrationY
	}
	return nil
}

func (m *ComfortRequest) GetHumanWeightedVibrationZ() []float64 {
	if m != nil {
		return m.HumanWeightedVibrationZ
	}
	return nil
}

type ComfortResponse struct {
	UnixTime             []float64          `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Rating               HabitibilityRating `protobuf:"varint,2,opt,name=rating,proto3,enum=comfortServiceAPI.v1.HabitibilityRating" json:"rating,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *ComfortResponse) Reset()         { *m = ComfortResponse{} }
func (m *ComfortResponse) String() string { return proto.CompactTextString(m) }
func (*ComfortResponse) ProtoMessage()    {}
func (*ComfortResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8c2e8f0330418358, []int{1}
}

func (m *ComfortResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ComfortResponse.Unmarshal(m, b)
}
func (m *ComfortResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ComfortResponse.Marshal(b, m, deterministic)
}
func (m *ComfortResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ComfortResponse.Merge(m, src)
}
func (m *ComfortResponse) XXX_Size() int {
	return xxx_messageInfo_ComfortResponse.Size(m)
}
func (m *ComfortResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ComfortResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ComfortResponse proto.InternalMessageInfo

func (m *ComfortResponse) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *ComfortResponse) GetRating() HabitibilityRating {
	if m != nil {
		return m.Rating
	}
	return HabitibilityRating_UNKNOWN_RATING
}

func init() {
	proto.RegisterEnum("comfortServiceAPI.v1.HabitibilityRating", HabitibilityRating_name, HabitibilityRating_value)
	proto.RegisterType((*ComfortRequest)(nil), "comfortServiceAPI.v1.ComfortRequest")
	proto.RegisterType((*ComfortResponse)(nil), "comfortServiceAPI.v1.ComfortResponse")
}

func init() {
	proto.RegisterFile("comfortService/proto/v1/comfort_service_api_v1.proto", fileDescriptor_8c2e8f0330418358)
}

var fileDescriptor_8c2e8f0330418358 = []byte{
	// 375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x92, 0xcd, 0xaa, 0xda, 0x40,
	0x1c, 0xc5, 0x1b, 0xb5, 0xd2, 0x0e, 0x68, 0x75, 0xb0, 0x1a, 0x74, 0x23, 0xd2, 0x82, 0x74, 0x11,
	0x89, 0xed, 0xce, 0x4d, 0xa3, 0x44, 0x0d, 0xd5, 0xa4, 0x8c, 0xf1, 0x93, 0xc2, 0x90, 0xd8, 0xa9,
	0x0e, 0x34, 0x1f, 0x4d, 0xc6, 0x54, 0xfb, 0x6e, 0x7d, 0x9b, 0xfb, 0x20, 0x17, 0x93, 0x28, 0x44,
	0x25, 0x77, 0x7b, 0xce, 0xf9, 0x0d, 0x9c, 0xff, 0x1c, 0xf0, 0x65, 0xeb, 0x58, 0xbf, 0x1c, 0x8f,
	0xcd, 0x88, 0x17, 0xd0, 0x2d, 0xe9, 0xb8, 0x9e, 0xc3, 0x9c, 0x4e, 0x20, 0x76, 0x62, 0x1d, 0xfb,
	0x91, 0x81, 0x0d, 0x97, 0xe2, 0x40, 0x14, 0x42, 0x1f, 0x56, 0x92, 0x94, 0xf4, 0x5d, 0x11, 0x02,
	0xb1, 0xf5, 0xc4, 0x81, 0xe2, 0x20, 0x32, 0x10, 0xf9, 0x73, 0x20, 0x3e, 0x83, 0x0d, 0xf0, 0xf6,
	0x60, 0xd3, 0x23, 0x66, 0xd4, 0x22, 0x3c, 0xd7, 0xcc, 0xb6, 0x39, 0xf4, 0xe6, 0x2c, 0xe8, 0xd4,
	0x22, 0xb0, 0x07, 0xea, 0xfb, 0x83, 0x65, 0xd8, 0xf8, 0x2f, 0xa1, 0xbb, 0x3d, 0x23, 0x3f, 0x71,
	0x40, 0x4d, 0xcf, 0x60, 0xd4, 0xb1, 0xf1, 0x91, 0xcf, 0x84, 0xe9, 0x5a, 0x98, 0x58, 0xc6, 0x81,
	0xc5, 0xc5, 0x5f, 0xa5, 0xc2, 0x27, 0x3e, 0x9b, 0x06, 0xaf, 0x53, 0xe1, 0x7f, 0x7c, 0x2e, 0x0d,
	0xde, 0xb4, 0x5c, 0xf0, 0xee, 0xda, 0xd2, 0x77, 0x1d, 0xdb, 0x27, 0xe9, 0x35, 0xbf, 0x82, 0xfc,
	0x19, 0xb5, 0x77, 0x7c, 0xa6, 0xc9, 0xb5, 0x8b, 0xdd, 0xb6, 0xf0, 0xe8, 0x7a, 0xc2, 0xd8, 0x30,
	0x29, 0xa3, 0x26, 0xfd, 0x4d, 0xd9, 0x09, 0x85, 0x79, 0x14, 0x73, 0x9f, 0xfe, 0x73, 0x00, 0xde,
	0xdb, 0x10, 0x82, 0xe2, 0x5c, 0xfd, 0xa6, 0x6a, 0x4b, 0x15, 0x23, 0x49, 0x57, 0xd4, 0x51, 0xe9,
	0x15, 0x7c, 0x0f, 0xca, 0xaa, 0xa6, 0xe3, 0xb9, 0x3a, 0xd0, 0xa6, 0x43, 0x0d, 0xe9, 0x52, 0x7f,
	0x22, 0x97, 0x38, 0x58, 0x07, 0xd5, 0xd9, 0x44, 0x19, 0x8d, 0xf5, 0xc9, 0xfa, 0xc6, 0xcb, 0x40,
	0x1e, 0x54, 0x86, 0x92, 0x82, 0xee, 0x9c, 0x2c, 0x2c, 0x83, 0x42, 0x52, 0xca, 0xc1, 0x2a, 0x80,
	0x0b, 0x19, 0xdd, 0x46, 0x5f, 0xc3, 0x06, 0xa8, 0xc9, 0x2b, 0x1d, 0xc9, 0x53, 0xf9, 0xee, 0x9d,
	0x7c, 0xd7, 0xbe, 0xee, 0x22, 0xae, 0x0c, 0x7f, 0x80, 0xc2, 0xe5, 0x86, 0x51, 0x97, 0x0f, 0x8f,
	0x8f, 0x92, 0x9c, 0x53, 0xfd, 0xe3, 0x0b, 0xa9, 0xe8, 0x3b, 0xfa, 0xad, 0x4d, 0xf3, 0x66, 0xd6,
	0x81, 0xd8, 0x4b, 0x2a, 0x66, 0x3e, 0x5c, 0xf2, 0xe7, 0xe7, 0x00, 0x00, 0x00, 0xff, 0xff, 0x9c,
	0x33, 0x0a, 0x17, 0x01, 0x03, 0x00, 0x00,
}
