// Code generated by protoc-gen-go. DO NOT EDIT.
// source: powerTrainAggregator/proto/v1/power_train_aggregator_api_v1.proto

package powerTrainAggregator

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type PTEstimateRequest struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Latitude             []float32 `protobuf:"fixed32,2,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            []float32 `protobuf:"fixed32,3,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Heading              []float32 `protobuf:"fixed32,4,rep,packed,name=heading,proto3" json:"heading,omitempty"`
	PropPitch            []float32 `protobuf:"fixed32,5,rep,packed,name=prop_pitch,json=propPitch,proto3" json:"prop_pitch,omitempty"`
	MotorSpeed           []float32 `protobuf:"fixed32,6,rep,packed,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	SOG                  []float32 `protobuf:"fixed32,7,rep,packed,name=SOG,proto3" json:"SOG,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PTEstimateRequest) Reset()         { *m = PTEstimateRequest{} }
func (m *PTEstimateRequest) String() string { return proto.CompactTextString(m) }
func (*PTEstimateRequest) ProtoMessage()    {}
func (*PTEstimateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e792ff39cbce58a, []int{0}
}

func (m *PTEstimateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTEstimateRequest.Unmarshal(m, b)
}
func (m *PTEstimateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTEstimateRequest.Marshal(b, m, deterministic)
}
func (m *PTEstimateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTEstimateRequest.Merge(m, src)
}
func (m *PTEstimateRequest) XXX_Size() int {
	return xxx_messageInfo_PTEstimateRequest.Size(m)
}
func (m *PTEstimateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PTEstimateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PTEstimateRequest proto.InternalMessageInfo

func (m *PTEstimateRequest) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *PTEstimateRequest) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *PTEstimateRequest) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *PTEstimateRequest) GetHeading() []float32 {
	if m != nil {
		return m.Heading
	}
	return nil
}

func (m *PTEstimateRequest) GetPropPitch() []float32 {
	if m != nil {
		return m.PropPitch
	}
	return nil
}

func (m *PTEstimateRequest) GetMotorSpeed() []float32 {
	if m != nil {
		return m.MotorSpeed
	}
	return nil
}

func (m *PTEstimateRequest) GetSOG() []float32 {
	if m != nil {
		return m.SOG
	}
	return nil
}

type PTEstimateResponse struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	PowerEstimate        []float32 `protobuf:"fixed32,2,rep,packed,name=power_estimate,json=powerEstimate,proto3" json:"power_estimate,omitempty"`
	CostEstimate         []float32 `protobuf:"fixed32,3,rep,packed,name=cost_estimate,json=costEstimate,proto3" json:"cost_estimate,omitempty"`
	TotalCost            float32   `protobuf:"fixed32,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *PTEstimateResponse) Reset()         { *m = PTEstimateResponse{} }
func (m *PTEstimateResponse) String() string { return proto.CompactTextString(m) }
func (*PTEstimateResponse) ProtoMessage()    {}
func (*PTEstimateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_5e792ff39cbce58a, []int{1}
}

func (m *PTEstimateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PTEstimateResponse.Unmarshal(m, b)
}
func (m *PTEstimateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PTEstimateResponse.Marshal(b, m, deterministic)
}
func (m *PTEstimateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PTEstimateResponse.Merge(m, src)
}
func (m *PTEstimateResponse) XXX_Size() int {
	return xxx_messageInfo_PTEstimateResponse.Size(m)
}
func (m *PTEstimateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PTEstimateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PTEstimateResponse proto.InternalMessageInfo

func (m *PTEstimateResponse) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *PTEstimateResponse) GetPowerEstimate() []float32 {
	if m != nil {
		return m.PowerEstimate
	}
	return nil
}

func (m *PTEstimateResponse) GetCostEstimate() []float32 {
	if m != nil {
		return m.CostEstimate
	}
	return nil
}

func (m *PTEstimateResponse) GetTotalCost() float32 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func init() {
	proto.RegisterType((*PTEstimateRequest)(nil), "powerTrainAggregator.v1.PTEstimateRequest")
	proto.RegisterType((*PTEstimateResponse)(nil), "powerTrainAggregator.v1.PTEstimateResponse")
}

func init() {
	proto.RegisterFile("powerTrainAggregator/proto/v1/power_train_aggregator_api_v1.proto", fileDescriptor_5e792ff39cbce58a)
}

var fileDescriptor_5e792ff39cbce58a = []byte{
	// 354 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0x53, 0xca, 0xe5, 0xcf, 0xb9, 0x97, 0x1b, 0x9c, 0x8d, 0x13, 0x94, 0x48, 0x30, 0x26,
	0x44, 0x63, 0x9b, 0xea, 0xd2, 0x15, 0x1a, 0xe3, 0x52, 0x02, 0xac, 0xdc, 0x34, 0x23, 0x9c, 0x94,
	0x49, 0x68, 0x67, 0x6c, 0x0f, 0xd5, 0xad, 0xef, 0xe1, 0x73, 0xf9, 0x3c, 0x66, 0xa6, 0x50, 0x4c,
	0x44, 0xe3, 0xae, 0xf3, 0xfb, 0x7d, 0x33, 0xe9, 0x37, 0x67, 0x60, 0xa8, 0xd5, 0x33, 0xa6, 0xd3,
	0x54, 0xc8, 0x64, 0x18, 0x45, 0x29, 0x46, 0x82, 0x54, 0xea, 0xeb, 0x54, 0x91, 0xf2, 0xf3, 0xc0,
	0xb7, 0x36, 0x24, 0xa3, 0x43, 0x51, 0xfa, 0x50, 0x68, 0x19, 0xe6, 0x81, 0x67, 0x63, 0x6c, 0x7f,
	0xd7, 0x11, 0x5e, 0x1e, 0xf4, 0xdf, 0x1d, 0xd8, 0x1b, 0x4d, 0x6f, 0x33, 0x92, 0xb1, 0x20, 0x1c,
	0xe3, 0xd3, 0x0a, 0x33, 0x62, 0x07, 0xd0, 0x5c, 0x25, 0xf2, 0x25, 0x24, 0x19, 0x23, 0x77, 0x7a,
	0xee, 0xc0, 0x19, 0x37, 0x0c, 0x98, 0xca, 0x18, 0x59, 0x07, 0x1a, 0x4b, 0x41, 0x92, 0x56, 0x73,
	0xe4, 0x95, 0x9e, 0x3b, 0xa8, 0x8c, 0xcb, 0x35, 0x3b, 0x84, 0xe6, 0x52, 0x25, 0x51, 0x21, 0x5d,
	0x2b, 0xb7, 0x80, 0x71, 0xa8, 0x2f, 0x50, 0xcc, 0x65, 0x12, 0xf1, 0xaa, 0x75, 0x9b, 0x25, 0xeb,
	0x02, 0xe8, 0x54, 0xe9, 0x50, 0x4b, 0x9a, 0x2d, 0xf8, 0x9f, 0x62, 0xa3, 0x21, 0x23, 0x03, 0xd8,
	0x11, 0xfc, 0x8d, 0x95, 0x29, 0x95, 0x69, 0xc4, 0x39, 0xaf, 0x59, 0x0f, 0x16, 0x4d, 0x0c, 0x61,
	0x6d, 0x70, 0x27, 0xf7, 0x77, 0xbc, 0x6e, 0x85, 0xf9, 0xec, 0xbf, 0x39, 0xc0, 0x3e, 0x17, 0xcb,
	0xb4, 0x4a, 0x32, 0xfc, 0xb9, 0xd9, 0x09, 0xfc, 0x2f, 0x2e, 0x13, 0xd7, 0xdb, 0xd6, 0xfd, 0x5a,
	0x96, 0x6e, 0xce, 0x62, 0xc7, 0xd0, 0x9a, 0xa9, 0x8c, 0xb6, 0xa9, 0xa2, 0xe8, 0x3f, 0x03, 0xcb,
	0x50, 0x17, 0x80, 0x14, 0x89, 0x65, 0x68, 0x28, 0xaf, 0xf6, 0x1c, 0xd3, 0xc8, 0x92, 0x1b, 0x95,
	0xd1, 0xc5, 0xab, 0x03, 0x6d, 0xf3, 0x7b, 0x36, 0x3c, 0xc1, 0x34, 0x97, 0x33, 0x64, 0x31, 0xb0,
	0xcd, 0xfe, 0x51, 0x39, 0x2f, 0x76, 0xea, 0x7d, 0x33, 0x3c, 0xef, 0xcb, 0xe0, 0x3a, 0x67, 0xbf,
	0xca, 0x16, 0x77, 0x71, 0xed, 0x3f, 0x9c, 0xef, 0x7c, 0x59, 0x79, 0xe0, 0x5f, 0xed, 0x12, 0x8f,
	0x35, 0xfb, 0x98, 0x2e, 0x3f, 0x02, 0x00, 0x00, 0xff, 0xff, 0x26, 0x49, 0x50, 0x05, 0x91, 0x02,
	0x00, 0x00,
}
