// source: power_train_aggregator_api_v1.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.powerTrainAggregatorAPI.v1.PTEstimateRequest', null, global);
goog.exportSymbol('proto.powerTrainAggregatorAPI.v1.PTEstimateResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.repeatedFields_, null);
};
goog.inherits(proto.powerTrainAggregatorAPI.v1.PTEstimateRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.displayName = 'proto.powerTrainAggregatorAPI.v1.PTEstimateRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.repeatedFields_, null);
};
goog.inherits(proto.powerTrainAggregatorAPI.v1.PTEstimateResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.displayName = 'proto.powerTrainAggregatorAPI.v1.PTEstimateResponse';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.repeatedFields_ = [1,2,3,4,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    unixTimeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    latitudeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    longitudeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    headingList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 4)) == null ? undefined : f,
    propPitchList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 5)) == null ? undefined : f,
    motorSpeedList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 6)) == null ? undefined : f,
    sogList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powerTrainAggregatorAPI.v1.PTEstimateRequest;
  return proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addUnixTime(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLatitude(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLongitude(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addHeading(values[i]);
      }
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPropPitch(values[i]);
      }
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addMotorSpeed(values[i]);
      }
      break;
    case 7:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSog(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnixTimeList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
  f = message.getLatitudeList();
  if (f.length > 0) {
    writer.writePackedFloat(
      2,
      f
    );
  }
  f = message.getLongitudeList();
  if (f.length > 0) {
    writer.writePackedFloat(
      3,
      f
    );
  }
  f = message.getHeadingList();
  if (f.length > 0) {
    writer.writePackedFloat(
      4,
      f
    );
  }
  f = message.getPropPitchList();
  if (f.length > 0) {
    writer.writePackedFloat(
      5,
      f
    );
  }
  f = message.getMotorSpeedList();
  if (f.length > 0) {
    writer.writePackedFloat(
      6,
      f
    );
  }
  f = message.getSogList();
  if (f.length > 0) {
    writer.writePackedFloat(
      7,
      f
    );
  }
};


/**
 * repeated double unix_time = 1;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getUnixTimeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setUnixTimeList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addUnixTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearUnixTimeList = function() {
  return this.setUnixTimeList([]);
};


/**
 * repeated float latitude = 2;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getLatitudeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setLatitudeList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addLatitude = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearLatitudeList = function() {
  return this.setLatitudeList([]);
};


/**
 * repeated float longitude = 3;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getLongitudeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setLongitudeList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addLongitude = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearLongitudeList = function() {
  return this.setLongitudeList([]);
};


/**
 * repeated float heading = 4;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getHeadingList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setHeadingList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addHeading = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearHeadingList = function() {
  return this.setHeadingList([]);
};


/**
 * repeated float prop_pitch = 5;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getPropPitchList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setPropPitchList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addPropPitch = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearPropPitchList = function() {
  return this.setPropPitchList([]);
};


/**
 * repeated float motor_speed = 6;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getMotorSpeedList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setMotorSpeedList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addMotorSpeed = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearMotorSpeedList = function() {
  return this.setMotorSpeedList([]);
};


/**
 * repeated float SOG = 7;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.getSogList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.setSogList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.addSog = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateRequest} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateRequest.prototype.clearSogList = function() {
  return this.setSogList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.repeatedFields_ = [1,2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    unixTimeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    powerEstimateList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    costEstimateList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    totalCost: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.powerTrainAggregatorAPI.v1.PTEstimateResponse;
  return proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addUnixTime(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPowerEstimate(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addCostEstimate(values[i]);
      }
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTotalCost(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnixTimeList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
  f = message.getPowerEstimateList();
  if (f.length > 0) {
    writer.writePackedFloat(
      2,
      f
    );
  }
  f = message.getCostEstimateList();
  if (f.length > 0) {
    writer.writePackedFloat(
      3,
      f
    );
  }
  f = message.getTotalCost();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * repeated double unix_time = 1;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.getUnixTimeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.setUnixTimeList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.addUnixTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.clearUnixTimeList = function() {
  return this.setUnixTimeList([]);
};


/**
 * repeated float power_estimate = 2;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.getPowerEstimateList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.setPowerEstimateList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.addPowerEstimate = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.clearPowerEstimateList = function() {
  return this.setPowerEstimateList([]);
};


/**
 * repeated float cost_estimate = 3;
 * @return {!Array<number>}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.getCostEstimateList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.setCostEstimateList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.addCostEstimate = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.clearCostEstimateList = function() {
  return this.setCostEstimateList([]);
};


/**
 * optional float total_cost = 4;
 * @return {number}
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.getTotalCost = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.powerTrainAggregatorAPI.v1.PTEstimateResponse} returns this
 */
proto.powerTrainAggregatorAPI.v1.PTEstimateResponse.prototype.setTotalCost = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


goog.object.extend(exports, proto.powerTrainAggregatorAPI.v1);
