// Code generated by protoc-gen-go. DO NOT EDIT.
// source: vesselMotionService/proto/v1/vessel_motion_service_api_v1.proto

package vesselMotionService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type LocationOnShipEnum int32

const (
	LocationOnShipEnum_UNKNOWN_LOCATION LocationOnShipEnum = 0
	LocationOnShipEnum_SOMEWHERE        LocationOnShipEnum = 1
)

var LocationOnShipEnum_name = map[int32]string{
	0: "UNKNOWN_LOCATION",
	1: "SOMEWHERE",
}

var LocationOnShipEnum_value = map[string]int32{
	"UNKNOWN_LOCATION": 0,
	"SOMEWHERE":        1,
}

func (x LocationOnShipEnum) String() string {
	return proto.EnumName(LocationOnShipEnum_name, int32(x))
}

func (LocationOnShipEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{0}
}

type ModelTypeEnum int32

const (
	ModelTypeEnum_UNKNOWN_MODEL ModelTypeEnum = 0
	ModelTypeEnum_OPENWATER     ModelTypeEnum = 1
	ModelTypeEnum_ICE           ModelTypeEnum = 2
)

var ModelTypeEnum_name = map[int32]string{
	0: "UNKNOWN_MODEL",
	1: "OPENWATER",
	2: "ICE",
}

var ModelTypeEnum_value = map[string]int32{
	"UNKNOWN_MODEL": 0,
	"OPENWATER":     1,
	"ICE":           2,
}

func (x ModelTypeEnum) String() string {
	return proto.EnumName(ModelTypeEnum_name, int32(x))
}

func (ModelTypeEnum) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{1}
}

type MotionEstimateRequest struct {
	PortPropMotorPower    []float32          `protobuf:"fixed32,1,rep,packed,name=port_prop_motor_power,json=portPropMotorPower,proto3" json:"port_prop_motor_power,omitempty"`
	WindSpeedRelative     []float32          `protobuf:"fixed32,2,rep,packed,name=wind_speed_relative,json=windSpeedRelative,proto3" json:"wind_speed_relative,omitempty"`
	Latitude              []float32          `protobuf:"fixed32,3,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Heading               []float32          `protobuf:"fixed32,4,rep,packed,name=heading,proto3" json:"heading,omitempty"`
	WaveHeight            []float32          `protobuf:"fixed32,5,rep,packed,name=wave_height,json=waveHeight,proto3" json:"wave_height,omitempty"`
	QueryLocation         LocationOnShipEnum `protobuf:"varint,6,opt,name=query_location,json=queryLocation,proto3,enum=vesselMotionService.v1.LocationOnShipEnum" json:"query_location,omitempty"`
	WindDirectionRelative []float32          `protobuf:"fixed32,7,rep,packed,name=wind_direction_relative,json=windDirectionRelative,proto3" json:"wind_direction_relative,omitempty"`
	ModelType             ModelTypeEnum      `protobuf:"varint,8,opt,name=model_type,json=modelType,proto3,enum=vesselMotionService.v1.ModelTypeEnum" json:"model_type,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}           `json:"-"`
	XXX_unrecognized      []byte             `json:"-"`
	XXX_sizecache         int32              `json:"-"`
}

func (m *MotionEstimateRequest) Reset()         { *m = MotionEstimateRequest{} }
func (m *MotionEstimateRequest) String() string { return proto.CompactTextString(m) }
func (*MotionEstimateRequest) ProtoMessage()    {}
func (*MotionEstimateRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{0}
}

func (m *MotionEstimateRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionEstimateRequest.Unmarshal(m, b)
}
func (m *MotionEstimateRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionEstimateRequest.Marshal(b, m, deterministic)
}
func (m *MotionEstimateRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionEstimateRequest.Merge(m, src)
}
func (m *MotionEstimateRequest) XXX_Size() int {
	return xxx_messageInfo_MotionEstimateRequest.Size(m)
}
func (m *MotionEstimateRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionEstimateRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MotionEstimateRequest proto.InternalMessageInfo

func (m *MotionEstimateRequest) GetPortPropMotorPower() []float32 {
	if m != nil {
		return m.PortPropMotorPower
	}
	return nil
}

func (m *MotionEstimateRequest) GetWindSpeedRelative() []float32 {
	if m != nil {
		return m.WindSpeedRelative
	}
	return nil
}

func (m *MotionEstimateRequest) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *MotionEstimateRequest) GetHeading() []float32 {
	if m != nil {
		return m.Heading
	}
	return nil
}

func (m *MotionEstimateRequest) GetWaveHeight() []float32 {
	if m != nil {
		return m.WaveHeight
	}
	return nil
}

func (m *MotionEstimateRequest) GetQueryLocation() LocationOnShipEnum {
	if m != nil {
		return m.QueryLocation
	}
	return LocationOnShipEnum_UNKNOWN_LOCATION
}

func (m *MotionEstimateRequest) GetWindDirectionRelative() []float32 {
	if m != nil {
		return m.WindDirectionRelative
	}
	return nil
}

func (m *MotionEstimateRequest) GetModelType() ModelTypeEnum {
	if m != nil {
		return m.ModelType
	}
	return ModelTypeEnum_UNKNOWN_MODEL
}

type MotionTrackingRequest struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MotionTrackingRequest) Reset()         { *m = MotionTrackingRequest{} }
func (m *MotionTrackingRequest) String() string { return proto.CompactTextString(m) }
func (*MotionTrackingRequest) ProtoMessage()    {}
func (*MotionTrackingRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{1}
}

func (m *MotionTrackingRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionTrackingRequest.Unmarshal(m, b)
}
func (m *MotionTrackingRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionTrackingRequest.Marshal(b, m, deterministic)
}
func (m *MotionTrackingRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionTrackingRequest.Merge(m, src)
}
func (m *MotionTrackingRequest) XXX_Size() int {
	return xxx_messageInfo_MotionTrackingRequest.Size(m)
}
func (m *MotionTrackingRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionTrackingRequest.DiscardUnknown(m)
}

var xxx_messageInfo_MotionTrackingRequest proto.InternalMessageInfo

type MotionEstimateResponse struct {
	// All accelerations returned in this message are provided in m/s^2
	AccelerationEstimateX []float64 `protobuf:"fixed64,1,rep,packed,name=acceleration_estimate_x,json=accelerationEstimateX,proto3" json:"acceleration_estimate_x,omitempty"`
	AccelerationEstimateY []float64 `protobuf:"fixed64,2,rep,packed,name=acceleration_estimate_y,json=accelerationEstimateY,proto3" json:"acceleration_estimate_y,omitempty"`
	AccelerationEstimateZ []float64 `protobuf:"fixed64,3,rep,packed,name=acceleration_estimate_z,json=accelerationEstimateZ,proto3" json:"acceleration_estimate_z,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *MotionEstimateResponse) Reset()         { *m = MotionEstimateResponse{} }
func (m *MotionEstimateResponse) String() string { return proto.CompactTextString(m) }
func (*MotionEstimateResponse) ProtoMessage()    {}
func (*MotionEstimateResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{2}
}

func (m *MotionEstimateResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionEstimateResponse.Unmarshal(m, b)
}
func (m *MotionEstimateResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionEstimateResponse.Marshal(b, m, deterministic)
}
func (m *MotionEstimateResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionEstimateResponse.Merge(m, src)
}
func (m *MotionEstimateResponse) XXX_Size() int {
	return xxx_messageInfo_MotionEstimateResponse.Size(m)
}
func (m *MotionEstimateResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionEstimateResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MotionEstimateResponse proto.InternalMessageInfo

func (m *MotionEstimateResponse) GetAccelerationEstimateX() []float64 {
	if m != nil {
		return m.AccelerationEstimateX
	}
	return nil
}

func (m *MotionEstimateResponse) GetAccelerationEstimateY() []float64 {
	if m != nil {
		return m.AccelerationEstimateY
	}
	return nil
}

func (m *MotionEstimateResponse) GetAccelerationEstimateZ() []float64 {
	if m != nil {
		return m.AccelerationEstimateZ
	}
	return nil
}

type MotionTrackingResponse struct {
	AccelerationActual   []float64 `protobuf:"fixed64,1,rep,packed,name=acceleration_actual,json=accelerationActual,proto3" json:"acceleration_actual,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MotionTrackingResponse) Reset()         { *m = MotionTrackingResponse{} }
func (m *MotionTrackingResponse) String() string { return proto.CompactTextString(m) }
func (*MotionTrackingResponse) ProtoMessage()    {}
func (*MotionTrackingResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{3}
}

func (m *MotionTrackingResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionTrackingResponse.Unmarshal(m, b)
}
func (m *MotionTrackingResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionTrackingResponse.Marshal(b, m, deterministic)
}
func (m *MotionTrackingResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionTrackingResponse.Merge(m, src)
}
func (m *MotionTrackingResponse) XXX_Size() int {
	return xxx_messageInfo_MotionTrackingResponse.Size(m)
}
func (m *MotionTrackingResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionTrackingResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MotionTrackingResponse proto.InternalMessageInfo

func (m *MotionTrackingResponse) GetAccelerationActual() []float64 {
	if m != nil {
		return m.AccelerationActual
	}
	return nil
}

type MotionEvaluationResponse struct {
	AccelerationEstimate []float64 `protobuf:"fixed64,1,rep,packed,name=acceleration_estimate,json=accelerationEstimate,proto3" json:"acceleration_estimate,omitempty"`
	AccelerationActual   []float64 `protobuf:"fixed64,2,rep,packed,name=acceleration_actual,json=accelerationActual,proto3" json:"acceleration_actual,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *MotionEvaluationResponse) Reset()         { *m = MotionEvaluationResponse{} }
func (m *MotionEvaluationResponse) String() string { return proto.CompactTextString(m) }
func (*MotionEvaluationResponse) ProtoMessage()    {}
func (*MotionEvaluationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_73084dfaedc4236f, []int{4}
}

func (m *MotionEvaluationResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MotionEvaluationResponse.Unmarshal(m, b)
}
func (m *MotionEvaluationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MotionEvaluationResponse.Marshal(b, m, deterministic)
}
func (m *MotionEvaluationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MotionEvaluationResponse.Merge(m, src)
}
func (m *MotionEvaluationResponse) XXX_Size() int {
	return xxx_messageInfo_MotionEvaluationResponse.Size(m)
}
func (m *MotionEvaluationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MotionEvaluationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MotionEvaluationResponse proto.InternalMessageInfo

func (m *MotionEvaluationResponse) GetAccelerationEstimate() []float64 {
	if m != nil {
		return m.AccelerationEstimate
	}
	return nil
}

func (m *MotionEvaluationResponse) GetAccelerationActual() []float64 {
	if m != nil {
		return m.AccelerationActual
	}
	return nil
}

func init() {
	proto.RegisterEnum("vesselMotionService.v1.LocationOnShipEnum", LocationOnShipEnum_name, LocationOnShipEnum_value)
	proto.RegisterEnum("vesselMotionService.v1.ModelTypeEnum", ModelTypeEnum_name, ModelTypeEnum_value)
	proto.RegisterType((*MotionEstimateRequest)(nil), "vesselMotionService.v1.MotionEstimateRequest")
	proto.RegisterType((*MotionTrackingRequest)(nil), "vesselMotionService.v1.MotionTrackingRequest")
	proto.RegisterType((*MotionEstimateResponse)(nil), "vesselMotionService.v1.MotionEstimateResponse")
	proto.RegisterType((*MotionTrackingResponse)(nil), "vesselMotionService.v1.MotionTrackingResponse")
	proto.RegisterType((*MotionEvaluationResponse)(nil), "vesselMotionService.v1.MotionEvaluationResponse")
}

func init() {
	proto.RegisterFile("vesselMotionService/proto/v1/vessel_motion_service_api_v1.proto", fileDescriptor_73084dfaedc4236f)
}

var fileDescriptor_73084dfaedc4236f = []byte{
	// 610 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x94, 0xdb, 0x6e, 0xd3, 0x4c,
	0x10, 0xc7, 0x3f, 0x27, 0x1f, 0x3d, 0x0c, 0x4a, 0x95, 0x6e, 0x9b, 0xd6, 0xea, 0x0d, 0x55, 0x24,
	0xa4, 0x2a, 0x12, 0x09, 0x69, 0x25, 0x24, 0xe0, 0x02, 0xf5, 0x60, 0xa9, 0x15, 0x4d, 0x5c, 0x9c,
	0xa0, 0x42, 0x6f, 0x56, 0x8b, 0x3d, 0x6a, 0x2c, 0x1c, 0xef, 0x76, 0x7d, 0x28, 0x81, 0x1b, 0x9e,
	0x85, 0x4b, 0x9e, 0x82, 0x87, 0xe2, 0x01, 0xd0, 0x6e, 0xec, 0xf4, 0x64, 0x2b, 0x70, 0x67, 0xef,
	0x6f, 0x66, 0xf6, 0x3f, 0xf3, 0x1f, 0x2d, 0xbc, 0x49, 0x31, 0x8a, 0x30, 0xe8, 0xf1, 0xd8, 0xe7,
	0xe1, 0x00, 0x65, 0xea, 0xbb, 0xd8, 0x11, 0x92, 0xc7, 0xbc, 0x93, 0x76, 0x3b, 0x53, 0x48, 0xc7,
	0x9a, 0xd2, 0x68, 0x8a, 0x29, 0x13, 0x3e, 0x4d, 0xbb, 0x6d, 0x1d, 0x45, 0x36, 0x0a, 0x0a, 0xb4,
	0xd3, 0x6e, 0xf3, 0x47, 0x15, 0x1a, 0xd3, 0x43, 0x2b, 0x8a, 0xfd, 0x31, 0x8b, 0xd1, 0xc1, 0xab,
	0x04, 0xa3, 0x98, 0x74, 0xa1, 0x21, 0xb8, 0x8c, 0xa9, 0x90, 0x5c, 0xa8, 0xd2, 0x5c, 0x52, 0xc1,
	0xaf, 0x51, 0x9a, 0xc6, 0x76, 0x75, 0xa7, 0xe2, 0x10, 0x05, 0xcf, 0x24, 0x17, 0x3d, 0x85, 0xce,
	0x14, 0x21, 0x6d, 0x58, 0xbb, 0xf6, 0x43, 0x8f, 0x46, 0x02, 0xd1, 0xa3, 0x12, 0x03, 0x16, 0xfb,
	0x29, 0x9a, 0x15, 0x9d, 0xb0, 0xaa, 0xd0, 0x40, 0x11, 0x27, 0x03, 0x64, 0x0b, 0x96, 0xd4, 0x57,
	0x9c, 0x78, 0x68, 0x56, 0x75, 0xd0, 0xec, 0x9f, 0x98, 0xb0, 0x38, 0x42, 0xe6, 0xf9, 0xe1, 0xa5,
	0xf9, 0xbf, 0x46, 0xf9, 0x2f, 0x79, 0x02, 0x8f, 0xaf, 0x59, 0x8a, 0x74, 0x84, 0xfe, 0xe5, 0x28,
	0x36, 0x1f, 0x69, 0x0a, 0xea, 0xe8, 0x58, 0x9f, 0x90, 0x77, 0xb0, 0x72, 0x95, 0xa0, 0x9c, 0xd0,
	0x80, 0xbb, 0x4c, 0xb5, 0x66, 0x2e, 0x6c, 0x1b, 0x3b, 0x2b, 0xbb, 0xad, 0x76, 0xf1, 0x10, 0xda,
	0xa7, 0x59, 0x9c, 0x1d, 0x0e, 0x46, 0xbe, 0xb0, 0xc2, 0x64, 0xec, 0xd4, 0x74, 0x85, 0x1c, 0x90,
	0x17, 0xb0, 0xa9, 0x3b, 0xf3, 0x7c, 0x89, 0xae, 0x9e, 0xf2, 0xac, 0xbb, 0x45, 0x7d, 0x7f, 0x43,
	0xe1, 0xa3, 0x9c, 0xce, 0x3a, 0x3c, 0x02, 0x18, 0x73, 0x0f, 0x03, 0x1a, 0x4f, 0x04, 0x9a, 0x4b,
	0x5a, 0xc6, 0xd3, 0x32, 0x19, 0x3d, 0x15, 0x39, 0x9c, 0x08, 0xd4, 0x0a, 0x96, 0xc7, 0xf9, 0x6f,
	0x73, 0x33, 0xf7, 0x68, 0x28, 0x99, 0xfb, 0xd9, 0x0f, 0x2f, 0x33, 0x8f, 0x9a, 0xbf, 0x0c, 0xd8,
	0xb8, 0xef, 0x5e, 0x24, 0x78, 0x18, 0xa1, 0x52, 0xcc, 0x5c, 0x17, 0x03, 0x94, 0xba, 0x03, 0x8a,
	0x59, 0x00, 0xfd, 0xa2, 0x0d, 0x34, 0x9c, 0xc6, 0x6d, 0x9c, 0xa7, 0x7f, 0x28, 0xcf, 0x9b, 0x68,
	0x1f, 0x4b, 0xf2, 0x3e, 0x96, 0xe7, 0x7d, 0xd5, 0xd6, 0x96, 0xe4, 0x5d, 0x34, 0x4f, 0xf2, 0x0e,
	0x6e, 0x7a, 0xcb, 0x3a, 0xe8, 0xc0, 0xda, 0x9d, 0x8a, 0xcc, 0x8d, 0x13, 0x16, 0x64, 0xea, 0xc9,
	0x6d, 0xb4, 0xaf, 0x49, 0xf3, 0xbb, 0x01, 0x66, 0x36, 0x8d, 0x94, 0x05, 0x09, 0x9b, 0x3a, 0x91,
	0x55, 0xdb, 0x83, 0x46, 0xa1, 0xbe, 0xac, 0xde, 0x7a, 0x91, 0xba, 0x32, 0x09, 0x95, 0x32, 0x09,
	0xad, 0x97, 0x40, 0x1e, 0x2e, 0x13, 0x59, 0x87, 0xfa, 0xfb, 0xfe, 0xdb, 0xbe, 0x7d, 0xde, 0xa7,
	0xa7, 0xf6, 0xe1, 0xfe, 0xf0, 0xc4, 0xee, 0xd7, 0xff, 0x23, 0x35, 0x58, 0x1e, 0xd8, 0x3d, 0xeb,
	0xfc, 0xd8, 0x72, 0xac, 0xba, 0xd1, 0x7a, 0x05, 0xb5, 0x3b, 0x0b, 0x40, 0x56, 0xa1, 0x96, 0x67,
	0xf5, 0xec, 0x23, 0xeb, 0x74, 0x9a, 0x62, 0x9f, 0x59, 0xfd, 0xf3, 0xfd, 0xa1, 0xe5, 0xd4, 0x0d,
	0xb2, 0x08, 0xd5, 0x93, 0x43, 0xab, 0x5e, 0xd9, 0xfd, 0x5d, 0x81, 0xb5, 0x82, 0xa5, 0x22, 0x1c,
	0x56, 0xee, 0xae, 0x07, 0x79, 0x56, 0xbe, 0x7c, 0x05, 0x8f, 0xc0, 0x56, 0xfb, 0x6f, 0xc3, 0xb3,
	0x29, 0xcf, 0x2e, 0xcc, 0xdd, 0x9c, 0x77, 0xe1, 0xbd, 0x8d, 0x9e, 0x77, 0xe1, 0x83, 0x25, 0xf9,
	0x36, 0xb3, 0x3c, 0x93, 0x72, 0x63, 0xfd, 0xbf, 0xf6, 0xfa, 0x7c, 0x4e, 0xf8, 0x83, 0x9d, 0x3a,
	0x38, 0xb8, 0x68, 0x15, 0xbd, 0xcb, 0x69, 0xf7, 0x75, 0xc1, 0xf1, 0xcf, 0x4a, 0x91, 0x45, 0x9f,
	0x16, 0xf4, 0xfb, 0xbc, 0xf7, 0x27, 0x00, 0x00, 0xff, 0xff, 0xc5, 0x07, 0x39, 0xe6, 0xe2, 0x05,
	0x00, 0x00,
}
