// Code generated by protoc-gen-go. DO NOT EDIT.
// source: webGateway/proto/v1/web_gateway_api_v1.proto

package webGateway

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type HabitibilityRating int32

const (
	HabitibilityRating_UNKNOWN_RATING          HabitibilityRating = 0
	HabitibilityRating_NOT_UNCOMFORTABLE       HabitibilityRating = 1
	HabitibilityRating_SLIGHTLY_UNCOMFORTABLE  HabitibilityRating = 2
	HabitibilityRating_FAIRLY_UNCOMFORTABLE    HabitibilityRating = 3
	HabitibilityRating_UNCOMFORTABLE           HabitibilityRating = 4
	HabitibilityRating_VERY_UNCOMFORTABLE      HabitibilityRating = 5
	HabitibilityRating_EXTREMELY_UNCOMFORTABLE HabitibilityRating = 6
)

var HabitibilityRating_name = map[int32]string{
	0: "UNKNOWN_RATING",
	1: "NOT_UNCOMFORTABLE",
	2: "SLIGHTLY_UNCOMFORTABLE",
	3: "FAIRLY_UNCOMFORTABLE",
	4: "UNCOMFORTABLE",
	5: "VERY_UNCOMFORTABLE",
	6: "EXTREMELY_UNCOMFORTABLE",
}

var HabitibilityRating_value = map[string]int32{
	"UNKNOWN_RATING":          0,
	"NOT_UNCOMFORTABLE":       1,
	"SLIGHTLY_UNCOMFORTABLE":  2,
	"FAIRLY_UNCOMFORTABLE":    3,
	"UNCOMFORTABLE":           4,
	"VERY_UNCOMFORTABLE":      5,
	"EXTREMELY_UNCOMFORTABLE": 6,
}

func (x HabitibilityRating) String() string {
	return proto.EnumName(HabitibilityRating_name, int32(x))
}

func (HabitibilityRating) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{0}
}

// Login
type LoginRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *LoginRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type LoginResponse struct {
	Permissions          string   `protobuf:"bytes,1,opt,name=permissions,proto3" json:"permissions,omitempty"`
	AccessToken          string   `protobuf:"bytes,2,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetPermissions() string {
	if m != nil {
		return m.Permissions
	}
	return ""
}

func (m *LoginResponse) GetAccessToken() string {
	if m != nil {
		return m.AccessToken
	}
	return ""
}

// Route Analysis Aggregator
type RouteAnalysisRequest struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Latitude             []float32 `protobuf:"fixed32,2,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            []float32 `protobuf:"fixed32,3,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Heading              []float32 `protobuf:"fixed32,4,rep,packed,name=heading,proto3" json:"heading,omitempty"`
	PropPitch            []float32 `protobuf:"fixed32,5,rep,packed,name=prop_pitch,json=propPitch,proto3" json:"prop_pitch,omitempty"`
	MotorSpeed           []float32 `protobuf:"fixed32,6,rep,packed,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	SOG                  []float32 `protobuf:"fixed32,7,rep,packed,name=SOG,proto3" json:"SOG,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RouteAnalysisRequest) Reset()         { *m = RouteAnalysisRequest{} }
func (m *RouteAnalysisRequest) String() string { return proto.CompactTextString(m) }
func (*RouteAnalysisRequest) ProtoMessage()    {}
func (*RouteAnalysisRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{2}
}

func (m *RouteAnalysisRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteAnalysisRequest.Unmarshal(m, b)
}
func (m *RouteAnalysisRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteAnalysisRequest.Marshal(b, m, deterministic)
}
func (m *RouteAnalysisRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteAnalysisRequest.Merge(m, src)
}
func (m *RouteAnalysisRequest) XXX_Size() int {
	return xxx_messageInfo_RouteAnalysisRequest.Size(m)
}
func (m *RouteAnalysisRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteAnalysisRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteAnalysisRequest proto.InternalMessageInfo

func (m *RouteAnalysisRequest) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *RouteAnalysisRequest) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *RouteAnalysisRequest) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *RouteAnalysisRequest) GetHeading() []float32 {
	if m != nil {
		return m.Heading
	}
	return nil
}

func (m *RouteAnalysisRequest) GetPropPitch() []float32 {
	if m != nil {
		return m.PropPitch
	}
	return nil
}

func (m *RouteAnalysisRequest) GetMotorSpeed() []float32 {
	if m != nil {
		return m.MotorSpeed
	}
	return nil
}

func (m *RouteAnalysisRequest) GetSOG() []float32 {
	if m != nil {
		return m.SOG
	}
	return nil
}

type RouteAnalysisResponse struct {
	UnixTime             []float64          `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	AveragePower         float32            `protobuf:"fixed32,2,opt,name=average_power,json=averagePower,proto3" json:"average_power,omitempty"`
	TotalCost            float32            `protobuf:"fixed32,3,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	AverageRmsX          float64            `protobuf:"fixed64,4,opt,name=average_rms_x,json=averageRmsX,proto3" json:"average_rms_x,omitempty"`
	AverageRmsY          float64            `protobuf:"fixed64,5,opt,name=average_rms_y,json=averageRmsY,proto3" json:"average_rms_y,omitempty"`
	AverageRmsZ          float64            `protobuf:"fixed64,6,opt,name=average_rms_z,json=averageRmsZ,proto3" json:"average_rms_z,omitempty"`
	ComfortLevel         HabitibilityRating `protobuf:"varint,7,opt,name=comfort_level,json=comfortLevel,proto3,enum=webGateway.v1.HabitibilityRating" json:"comfort_level,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *RouteAnalysisResponse) Reset()         { *m = RouteAnalysisResponse{} }
func (m *RouteAnalysisResponse) String() string { return proto.CompactTextString(m) }
func (*RouteAnalysisResponse) ProtoMessage()    {}
func (*RouteAnalysisResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{3}
}

func (m *RouteAnalysisResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteAnalysisResponse.Unmarshal(m, b)
}
func (m *RouteAnalysisResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteAnalysisResponse.Marshal(b, m, deterministic)
}
func (m *RouteAnalysisResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteAnalysisResponse.Merge(m, src)
}
func (m *RouteAnalysisResponse) XXX_Size() int {
	return xxx_messageInfo_RouteAnalysisResponse.Size(m)
}
func (m *RouteAnalysisResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteAnalysisResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteAnalysisResponse proto.InternalMessageInfo

func (m *RouteAnalysisResponse) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *RouteAnalysisResponse) GetAveragePower() float32 {
	if m != nil {
		return m.AveragePower
	}
	return 0
}

func (m *RouteAnalysisResponse) GetTotalCost() float32 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

func (m *RouteAnalysisResponse) GetAverageRmsX() float64 {
	if m != nil {
		return m.AverageRmsX
	}
	return 0
}

func (m *RouteAnalysisResponse) GetAverageRmsY() float64 {
	if m != nil {
		return m.AverageRmsY
	}
	return 0
}

func (m *RouteAnalysisResponse) GetAverageRmsZ() float64 {
	if m != nil {
		return m.AverageRmsZ
	}
	return 0
}

func (m *RouteAnalysisResponse) GetComfortLevel() HabitibilityRating {
	if m != nil {
		return m.ComfortLevel
	}
	return HabitibilityRating_UNKNOWN_RATING
}

// Power Train Aggregator
type RoutePowerRequest struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Latitude             []float32 `protobuf:"fixed32,2,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            []float32 `protobuf:"fixed32,3,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Heading              []float32 `protobuf:"fixed32,4,rep,packed,name=heading,proto3" json:"heading,omitempty"`
	PropPitch            []float32 `protobuf:"fixed32,5,rep,packed,name=prop_pitch,json=propPitch,proto3" json:"prop_pitch,omitempty"`
	MotorSpeed           []float32 `protobuf:"fixed32,6,rep,packed,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	SOG                  []float32 `protobuf:"fixed32,7,rep,packed,name=SOG,proto3" json:"SOG,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoutePowerRequest) Reset()         { *m = RoutePowerRequest{} }
func (m *RoutePowerRequest) String() string { return proto.CompactTextString(m) }
func (*RoutePowerRequest) ProtoMessage()    {}
func (*RoutePowerRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{4}
}

func (m *RoutePowerRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutePowerRequest.Unmarshal(m, b)
}
func (m *RoutePowerRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutePowerRequest.Marshal(b, m, deterministic)
}
func (m *RoutePowerRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutePowerRequest.Merge(m, src)
}
func (m *RoutePowerRequest) XXX_Size() int {
	return xxx_messageInfo_RoutePowerRequest.Size(m)
}
func (m *RoutePowerRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutePowerRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RoutePowerRequest proto.InternalMessageInfo

func (m *RoutePowerRequest) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *RoutePowerRequest) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *RoutePowerRequest) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *RoutePowerRequest) GetHeading() []float32 {
	if m != nil {
		return m.Heading
	}
	return nil
}

func (m *RoutePowerRequest) GetPropPitch() []float32 {
	if m != nil {
		return m.PropPitch
	}
	return nil
}

func (m *RoutePowerRequest) GetMotorSpeed() []float32 {
	if m != nil {
		return m.MotorSpeed
	}
	return nil
}

func (m *RoutePowerRequest) GetSOG() []float32 {
	if m != nil {
		return m.SOG
	}
	return nil
}

type RoutePowerResponse struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	PowerEstimate        []float32 `protobuf:"fixed32,2,rep,packed,name=power_estimate,json=powerEstimate,proto3" json:"power_estimate,omitempty"`
	CostEstimate         []float32 `protobuf:"fixed32,3,rep,packed,name=cost_estimate,json=costEstimate,proto3" json:"cost_estimate,omitempty"`
	TotalCost            float32   `protobuf:"fixed32,4,opt,name=total_cost,json=totalCost,proto3" json:"total_cost,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RoutePowerResponse) Reset()         { *m = RoutePowerResponse{} }
func (m *RoutePowerResponse) String() string { return proto.CompactTextString(m) }
func (*RoutePowerResponse) ProtoMessage()    {}
func (*RoutePowerResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{5}
}

func (m *RoutePowerResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RoutePowerResponse.Unmarshal(m, b)
}
func (m *RoutePowerResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RoutePowerResponse.Marshal(b, m, deterministic)
}
func (m *RoutePowerResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RoutePowerResponse.Merge(m, src)
}
func (m *RoutePowerResponse) XXX_Size() int {
	return xxx_messageInfo_RoutePowerResponse.Size(m)
}
func (m *RoutePowerResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RoutePowerResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RoutePowerResponse proto.InternalMessageInfo

func (m *RoutePowerResponse) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *RoutePowerResponse) GetPowerEstimate() []float32 {
	if m != nil {
		return m.PowerEstimate
	}
	return nil
}

func (m *RoutePowerResponse) GetCostEstimate() []float32 {
	if m != nil {
		return m.CostEstimate
	}
	return nil
}

func (m *RoutePowerResponse) GetTotalCost() float32 {
	if m != nil {
		return m.TotalCost
	}
	return 0
}

// Vessel Motion Aggregator
type RouteMotionRequest struct {
	UnixTime             []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	Latitude             []float32 `protobuf:"fixed32,2,rep,packed,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            []float32 `protobuf:"fixed32,3,rep,packed,name=longitude,proto3" json:"longitude,omitempty"`
	Heading              []float32 `protobuf:"fixed32,4,rep,packed,name=heading,proto3" json:"heading,omitempty"`
	PropPitch            []float32 `protobuf:"fixed32,5,rep,packed,name=prop_pitch,json=propPitch,proto3" json:"prop_pitch,omitempty"`
	MotorSpeed           []float32 `protobuf:"fixed32,6,rep,packed,name=motor_speed,json=motorSpeed,proto3" json:"motor_speed,omitempty"`
	SOG                  []float32 `protobuf:"fixed32,7,rep,packed,name=SOG,proto3" json:"SOG,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *RouteMotionRequest) Reset()         { *m = RouteMotionRequest{} }
func (m *RouteMotionRequest) String() string { return proto.CompactTextString(m) }
func (*RouteMotionRequest) ProtoMessage()    {}
func (*RouteMotionRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{6}
}

func (m *RouteMotionRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteMotionRequest.Unmarshal(m, b)
}
func (m *RouteMotionRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteMotionRequest.Marshal(b, m, deterministic)
}
func (m *RouteMotionRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteMotionRequest.Merge(m, src)
}
func (m *RouteMotionRequest) XXX_Size() int {
	return xxx_messageInfo_RouteMotionRequest.Size(m)
}
func (m *RouteMotionRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteMotionRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RouteMotionRequest proto.InternalMessageInfo

func (m *RouteMotionRequest) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *RouteMotionRequest) GetLatitude() []float32 {
	if m != nil {
		return m.Latitude
	}
	return nil
}

func (m *RouteMotionRequest) GetLongitude() []float32 {
	if m != nil {
		return m.Longitude
	}
	return nil
}

func (m *RouteMotionRequest) GetHeading() []float32 {
	if m != nil {
		return m.Heading
	}
	return nil
}

func (m *RouteMotionRequest) GetPropPitch() []float32 {
	if m != nil {
		return m.PropPitch
	}
	return nil
}

func (m *RouteMotionRequest) GetMotorSpeed() []float32 {
	if m != nil {
		return m.MotorSpeed
	}
	return nil
}

func (m *RouteMotionRequest) GetSOG() []float32 {
	if m != nil {
		return m.SOG
	}
	return nil
}

type RouteMotionResponse struct {
	UnixTime              []float64 `protobuf:"fixed64,1,rep,packed,name=unix_time,json=unixTime,proto3" json:"unix_time,omitempty"`
	AccelerationEstimateX []float64 `protobuf:"fixed64,2,rep,packed,name=acceleration_estimate_x,json=accelerationEstimateX,proto3" json:"acceleration_estimate_x,omitempty"`
	AccelerationEstimateY []float64 `protobuf:"fixed64,3,rep,packed,name=acceleration_estimate_y,json=accelerationEstimateY,proto3" json:"acceleration_estimate_y,omitempty"`
	AccelerationEstimateZ []float64 `protobuf:"fixed64,4,rep,packed,name=acceleration_estimate_z,json=accelerationEstimateZ,proto3" json:"acceleration_estimate_z,omitempty"`
	XXX_NoUnkeyedLiteral  struct{}  `json:"-"`
	XXX_unrecognized      []byte    `json:"-"`
	XXX_sizecache         int32     `json:"-"`
}

func (m *RouteMotionResponse) Reset()         { *m = RouteMotionResponse{} }
func (m *RouteMotionResponse) String() string { return proto.CompactTextString(m) }
func (*RouteMotionResponse) ProtoMessage()    {}
func (*RouteMotionResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f42c0414ca895e1a, []int{7}
}

func (m *RouteMotionResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RouteMotionResponse.Unmarshal(m, b)
}
func (m *RouteMotionResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RouteMotionResponse.Marshal(b, m, deterministic)
}
func (m *RouteMotionResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RouteMotionResponse.Merge(m, src)
}
func (m *RouteMotionResponse) XXX_Size() int {
	return xxx_messageInfo_RouteMotionResponse.Size(m)
}
func (m *RouteMotionResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RouteMotionResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RouteMotionResponse proto.InternalMessageInfo

func (m *RouteMotionResponse) GetUnixTime() []float64 {
	if m != nil {
		return m.UnixTime
	}
	return nil
}

func (m *RouteMotionResponse) GetAccelerationEstimateX() []float64 {
	if m != nil {
		return m.AccelerationEstimateX
	}
	return nil
}

func (m *RouteMotionResponse) GetAccelerationEstimateY() []float64 {
	if m != nil {
		return m.AccelerationEstimateY
	}
	return nil
}

func (m *RouteMotionResponse) GetAccelerationEstimateZ() []float64 {
	if m != nil {
		return m.AccelerationEstimateZ
	}
	return nil
}

func init() {
	proto.RegisterEnum("webGateway.v1.HabitibilityRating", HabitibilityRating_name, HabitibilityRating_value)
	proto.RegisterType((*LoginRequest)(nil), "webGateway.v1.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "webGateway.v1.LoginResponse")
	proto.RegisterType((*RouteAnalysisRequest)(nil), "webGateway.v1.RouteAnalysisRequest")
	proto.RegisterType((*RouteAnalysisResponse)(nil), "webGateway.v1.RouteAnalysisResponse")
	proto.RegisterType((*RoutePowerRequest)(nil), "webGateway.v1.RoutePowerRequest")
	proto.RegisterType((*RoutePowerResponse)(nil), "webGateway.v1.RoutePowerResponse")
	proto.RegisterType((*RouteMotionRequest)(nil), "webGateway.v1.RouteMotionRequest")
	proto.RegisterType((*RouteMotionResponse)(nil), "webGateway.v1.RouteMotionResponse")
}

func init() {
	proto.RegisterFile("webGateway/proto/v1/web_gateway_api_v1.proto", fileDescriptor_f42c0414ca895e1a)
}

var fileDescriptor_f42c0414ca895e1a = []byte{
	// 789 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xdc, 0x56, 0xef, 0x6e, 0xe2, 0x46,
	0x10, 0xaf, 0xf9, 0x97, 0x63, 0x80, 0x28, 0xd9, 0x5e, 0x2e, 0x16, 0xb9, 0xaa, 0xc4, 0xd7, 0x4a,
	0xa8, 0xaa, 0x88, 0x48, 0xa5, 0x7e, 0xe9, 0x27, 0x72, 0x02, 0x2e, 0x2a, 0x81, 0xeb, 0xe2, 0x6b,
	0x13, 0xbe, 0x58, 0x0b, 0x6c, 0x7d, 0xab, 0xda, 0x5e, 0xd7, 0xbb, 0x40, 0xb8, 0x67, 0xe9, 0x23,
	0xf4, 0x15, 0xfa, 0x1a, 0xad, 0xda, 0xa7, 0xa9, 0xbc, 0x36, 0x60, 0x1c, 0x40, 0xf7, 0xf9, 0xbe,
	0x31, 0xbf, 0xdf, 0x6f, 0x66, 0x67, 0x86, 0xd9, 0x1d, 0xc3, 0xb7, 0x0b, 0x3a, 0xee, 0x12, 0x49,
	0x17, 0x64, 0x79, 0xe5, 0x07, 0x5c, 0xf2, 0xab, 0x79, 0xf3, 0x6a, 0x41, 0xc7, 0x96, 0x1d, 0x81,
	0x16, 0xf1, 0x99, 0x35, 0x6f, 0x36, 0x14, 0x87, 0x2a, 0x1b, 0x75, 0x63, 0xde, 0x34, 0x3a, 0x50,
	0xee, 0x71, 0x9b, 0x79, 0x98, 0xfe, 0x3e, 0xa3, 0x42, 0xa2, 0x2a, 0x3c, 0x9b, 0x09, 0x1a, 0x78,
	0xc4, 0xa5, 0xba, 0x56, 0xd3, 0xea, 0x45, 0xbc, 0xb6, 0x43, 0xce, 0x27, 0x42, 0x2c, 0x78, 0x30,
	0xd5, 0x33, 0x11, 0xb7, 0xb2, 0x0d, 0x13, 0x2a, 0x71, 0x1c, 0xe1, 0x73, 0x4f, 0x50, 0x54, 0x83,
	0x92, 0x4f, 0x03, 0x97, 0x09, 0xc1, 0xb8, 0x27, 0xe2, 0x58, 0x49, 0x08, 0x5d, 0x42, 0x99, 0x4c,
	0x26, 0x54, 0x08, 0x4b, 0xf2, 0xdf, 0xa8, 0x17, 0x87, 0x2c, 0x45, 0x98, 0x19, 0x42, 0xc6, 0xbf,
	0x1a, 0x3c, 0xc7, 0x7c, 0x26, 0x69, 0xcb, 0x23, 0xce, 0x52, 0x30, 0xb1, 0x4a, 0xf3, 0x02, 0x8a,
	0x33, 0x8f, 0x3d, 0x5a, 0x92, 0xa9, 0x3c, 0xb3, 0x75, 0x0d, 0x3f, 0x0b, 0x01, 0x93, 0x45, 0x79,
	0x3a, 0x44, 0x32, 0x39, 0x9b, 0x52, 0x3d, 0x53, 0xcb, 0xd6, 0x33, 0x78, 0x6d, 0xa3, 0x97, 0x50,
	0x74, 0xb8, 0x67, 0x47, 0x64, 0x56, 0x91, 0x1b, 0x00, 0xe9, 0x70, 0xf4, 0x9e, 0x92, 0x29, 0xf3,
	0x6c, 0x3d, 0xa7, 0xb8, 0x95, 0x89, 0xbe, 0x00, 0xf0, 0x03, 0xee, 0x5b, 0x3e, 0x93, 0x93, 0xf7,
	0x7a, 0x3e, 0x72, 0x0c, 0x91, 0xb7, 0x21, 0x80, 0xbe, 0x84, 0x92, 0xcb, 0x25, 0x0f, 0x2c, 0xe1,
	0x53, 0x3a, 0xd5, 0x0b, 0x8a, 0x07, 0x05, 0x0d, 0x43, 0x04, 0x9d, 0x40, 0x76, 0x38, 0xe8, 0xea,
	0x47, 0x8a, 0x08, 0x7f, 0x1a, 0x7f, 0x66, 0xe0, 0x2c, 0x55, 0x5b, 0xdc, 0xba, 0x83, 0xc5, 0xbd,
	0x82, 0x0a, 0x99, 0xd3, 0x80, 0xd8, 0xd4, 0xf2, 0xf9, 0x82, 0x06, 0xaa, 0x6d, 0x19, 0x5c, 0x8e,
	0xc1, 0xb7, 0x21, 0x16, 0x66, 0x2b, 0xb9, 0x24, 0x8e, 0x35, 0xe1, 0x42, 0xea, 0x59, 0xa5, 0x28,
	0x2a, 0xe4, 0x35, 0x17, 0x12, 0x19, 0x9b, 0x18, 0x81, 0x2b, 0xac, 0x47, 0x3d, 0x57, 0xd3, 0xea,
	0x1a, 0x2e, 0xc5, 0x20, 0x76, 0xc5, 0x7d, 0x5a, 0xb3, 0xd4, 0xf3, 0x69, 0xcd, 0x43, 0x5a, 0xf3,
	0x41, 0x2f, 0xa4, 0x35, 0x23, 0xd4, 0x81, 0xca, 0x84, 0xbb, 0xbf, 0xf2, 0x40, 0x5a, 0x0e, 0x9d,
	0x53, 0x47, 0x3f, 0xaa, 0x69, 0xf5, 0xe3, 0xeb, 0xcb, 0xc6, 0xd6, 0x1c, 0x36, 0xde, 0x90, 0x31,
	0x93, 0x6c, 0xcc, 0x1c, 0x26, 0x97, 0x98, 0x48, 0xe6, 0xd9, 0xb8, 0x1c, 0xfb, 0xf5, 0x42, 0x37,
	0xe3, 0x6f, 0x0d, 0x4e, 0x55, 0xbb, 0x54, 0x85, 0x9f, 0xd0, 0x1c, 0xfc, 0xa1, 0x01, 0x4a, 0x16,
	0xf6, 0x31, 0x43, 0xf0, 0x35, 0x1c, 0xab, 0x3f, 0xdf, 0xa2, 0x42, 0x32, 0x97, 0xc8, 0x55, 0x7d,
	0x15, 0x85, 0xb6, 0x63, 0x30, 0x9c, 0x95, 0x70, 0x00, 0x36, 0xaa, 0xa8, 0xd0, 0x72, 0x08, 0xae,
	0x45, 0xdb, 0xb3, 0x92, 0x4b, 0xcd, 0x8a, 0xf1, 0xcf, 0x2a, 0xbd, 0x3b, 0x2e, 0x19, 0xf7, 0x3e,
	0xa1, 0xc6, 0xff, 0xa7, 0xc1, 0xe7, 0x5b, 0x95, 0x7d, 0x4c, 0xe7, 0xbf, 0x87, 0xf3, 0xf0, 0x81,
	0x72, 0x68, 0x40, 0x42, 0xa7, 0x75, 0x6b, 0xad, 0x47, 0x55, 0xa9, 0x86, 0xcf, 0x92, 0xf4, 0xaa,
	0xc9, 0xf7, 0xfb, 0xfd, 0x96, 0xaa, 0x09, 0x7b, 0xfc, 0x1e, 0xf6, 0xfb, 0x7d, 0x50, 0x0d, 0xda,
	0xe3, 0x37, 0xfa, 0xe6, 0x2f, 0x0d, 0xd0, 0xd3, 0x3b, 0x85, 0x10, 0x1c, 0xbf, 0xeb, 0xff, 0xd8,
	0x1f, 0xfc, 0xd2, 0xb7, 0x70, 0xcb, 0xbc, 0xed, 0x77, 0x4f, 0x3e, 0x43, 0x67, 0x70, 0xda, 0x1f,
	0x98, 0xd6, 0xbb, 0xfe, 0xeb, 0xc1, 0x5d, 0x67, 0x80, 0xcd, 0xd6, 0x4d, 0xaf, 0x7d, 0xa2, 0xa1,
	0x2a, 0xbc, 0x18, 0xf6, 0x6e, 0xbb, 0x6f, 0xcc, 0xde, 0x43, 0x8a, 0xcb, 0x20, 0x1d, 0x9e, 0x77,
	0x5a, 0xb7, 0xf8, 0x09, 0x93, 0x45, 0xa7, 0x50, 0xd9, 0x86, 0x72, 0xe8, 0x05, 0xa0, 0x9f, 0xdb,
	0x38, 0x2d, 0xcd, 0xa3, 0x0b, 0x38, 0x6f, 0xdf, 0x9b, 0xb8, 0x7d, 0xd7, 0x7e, 0x12, 0xa7, 0x70,
	0x8d, 0xe3, 0xbd, 0x34, 0xa4, 0xc1, 0x9c, 0x4d, 0x28, 0xba, 0x81, 0xbc, 0xb2, 0xd1, 0x45, 0xea,
	0xe1, 0x48, 0x6e, 0xaf, 0xea, 0xcb, 0xdd, 0x64, 0xf4, 0xc7, 0x5e, 0xcf, 0xe0, 0x7c, 0xeb, 0xc1,
	0x6d, 0xd9, 0x76, 0x40, 0x6d, 0x22, 0x79, 0x80, 0x46, 0x50, 0xd9, 0xa2, 0xd0, 0xab, 0x54, 0xa4,
	0x5d, 0x5b, 0xa8, 0xfa, 0xd5, 0x61, 0x51, 0x7c, 0x2c, 0x8b, 0x77, 0x98, 0xba, 0xdf, 0x89, 0x33,
	0x7f, 0x02, 0xd8, 0xe0, 0xa8, 0xb6, 0x2b, 0x56, 0xf2, 0xad, 0xab, 0x5e, 0x1e, 0x50, 0xc4, 0x47,
	0xb9, 0xf1, 0x4a, 0x89, 0x26, 0x3a, 0x71, 0x96, 0x09, 0xa5, 0x04, 0x81, 0x76, 0x86, 0xda, 0xba,
	0xe0, 0x55, 0xe3, 0x90, 0x24, 0x3a, 0xee, 0xa6, 0x3a, 0xd2, 0x13, 0xdf, 0x1e, 0xf3, 0xe6, 0x0f,
	0x1b, 0x6b, 0x5c, 0x50, 0x9f, 0x1b, 0xdf, 0xfd, 0x1f, 0x00, 0x00, 0xff, 0xff, 0x63, 0xbc, 0xf0,
	0xdd, 0x9e, 0x08, 0x00, 0x00,
}
