// source: web_gateway_api_v1.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

goog.exportSymbol('proto.webGateway.v1.HabitibilityRating', null, global);
goog.exportSymbol('proto.webGateway.v1.LoginRequest', null, global);
goog.exportSymbol('proto.webGateway.v1.LoginResponse', null, global);
goog.exportSymbol('proto.webGateway.v1.RouteAnalysisRequest', null, global);
goog.exportSymbol('proto.webGateway.v1.RouteAnalysisResponse', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webGateway.v1.LoginRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.webGateway.v1.LoginRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.webGateway.v1.LoginRequest.displayName = 'proto.webGateway.v1.LoginRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webGateway.v1.LoginResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.webGateway.v1.LoginResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.webGateway.v1.LoginResponse.displayName = 'proto.webGateway.v1.LoginResponse';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webGateway.v1.RouteAnalysisRequest = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.webGateway.v1.RouteAnalysisRequest.repeatedFields_, null);
};
goog.inherits(proto.webGateway.v1.RouteAnalysisRequest, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.webGateway.v1.RouteAnalysisRequest.displayName = 'proto.webGateway.v1.RouteAnalysisRequest';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.webGateway.v1.RouteAnalysisResponse = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.webGateway.v1.RouteAnalysisResponse.repeatedFields_, null);
};
goog.inherits(proto.webGateway.v1.RouteAnalysisResponse, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.webGateway.v1.RouteAnalysisResponse.displayName = 'proto.webGateway.v1.RouteAnalysisResponse';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webGateway.v1.LoginRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.webGateway.v1.LoginRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webGateway.v1.LoginRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.LoginRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    username: jspb.Message.getFieldWithDefault(msg, 1, ""),
    password: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webGateway.v1.LoginRequest}
 */
proto.webGateway.v1.LoginRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webGateway.v1.LoginRequest;
  return proto.webGateway.v1.LoginRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webGateway.v1.LoginRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webGateway.v1.LoginRequest}
 */
proto.webGateway.v1.LoginRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUsername(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setPassword(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webGateway.v1.LoginRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webGateway.v1.LoginRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webGateway.v1.LoginRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.LoginRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUsername();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getPassword();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string username = 1;
 * @return {string}
 */
proto.webGateway.v1.LoginRequest.prototype.getUsername = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.webGateway.v1.LoginRequest} returns this
 */
proto.webGateway.v1.LoginRequest.prototype.setUsername = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string password = 2;
 * @return {string}
 */
proto.webGateway.v1.LoginRequest.prototype.getPassword = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.webGateway.v1.LoginRequest} returns this
 */
proto.webGateway.v1.LoginRequest.prototype.setPassword = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webGateway.v1.LoginResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.webGateway.v1.LoginResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webGateway.v1.LoginResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.LoginResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    permissions: jspb.Message.getFieldWithDefault(msg, 1, ""),
    accessToken: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webGateway.v1.LoginResponse}
 */
proto.webGateway.v1.LoginResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webGateway.v1.LoginResponse;
  return proto.webGateway.v1.LoginResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webGateway.v1.LoginResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webGateway.v1.LoginResponse}
 */
proto.webGateway.v1.LoginResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setPermissions(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setAccessToken(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webGateway.v1.LoginResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webGateway.v1.LoginResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webGateway.v1.LoginResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.LoginResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPermissions();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getAccessToken();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string permissions = 1;
 * @return {string}
 */
proto.webGateway.v1.LoginResponse.prototype.getPermissions = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.webGateway.v1.LoginResponse} returns this
 */
proto.webGateway.v1.LoginResponse.prototype.setPermissions = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string access_token = 2;
 * @return {string}
 */
proto.webGateway.v1.LoginResponse.prototype.getAccessToken = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.webGateway.v1.LoginResponse} returns this
 */
proto.webGateway.v1.LoginResponse.prototype.setAccessToken = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.webGateway.v1.RouteAnalysisRequest.repeatedFields_ = [1,2,3,4,5,6,7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.toObject = function(opt_includeInstance) {
  return proto.webGateway.v1.RouteAnalysisRequest.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webGateway.v1.RouteAnalysisRequest} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.RouteAnalysisRequest.toObject = function(includeInstance, msg) {
  var f, obj = {
    unixTimeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    latitudeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 2)) == null ? undefined : f,
    longitudeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 3)) == null ? undefined : f,
    headingList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 4)) == null ? undefined : f,
    propPitchList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 5)) == null ? undefined : f,
    motorSpeedList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 6)) == null ? undefined : f,
    sogList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 7)) == null ? undefined : f
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest}
 */
proto.webGateway.v1.RouteAnalysisRequest.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webGateway.v1.RouteAnalysisRequest;
  return proto.webGateway.v1.RouteAnalysisRequest.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webGateway.v1.RouteAnalysisRequest} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest}
 */
proto.webGateway.v1.RouteAnalysisRequest.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addUnixTime(values[i]);
      }
      break;
    case 2:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLatitude(values[i]);
      }
      break;
    case 3:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addLongitude(values[i]);
      }
      break;
    case 4:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addHeading(values[i]);
      }
      break;
    case 5:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addPropPitch(values[i]);
      }
      break;
    case 6:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addMotorSpeed(values[i]);
      }
      break;
    case 7:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedFloat() : [reader.readFloat()]);
      for (var i = 0; i < values.length; i++) {
        msg.addSog(values[i]);
      }
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webGateway.v1.RouteAnalysisRequest.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webGateway.v1.RouteAnalysisRequest} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.RouteAnalysisRequest.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnixTimeList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
  f = message.getLatitudeList();
  if (f.length > 0) {
    writer.writePackedFloat(
      2,
      f
    );
  }
  f = message.getLongitudeList();
  if (f.length > 0) {
    writer.writePackedFloat(
      3,
      f
    );
  }
  f = message.getHeadingList();
  if (f.length > 0) {
    writer.writePackedFloat(
      4,
      f
    );
  }
  f = message.getPropPitchList();
  if (f.length > 0) {
    writer.writePackedFloat(
      5,
      f
    );
  }
  f = message.getMotorSpeedList();
  if (f.length > 0) {
    writer.writePackedFloat(
      6,
      f
    );
  }
  f = message.getSogList();
  if (f.length > 0) {
    writer.writePackedFloat(
      7,
      f
    );
  }
};


/**
 * repeated double unix_time = 1;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getUnixTimeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setUnixTimeList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addUnixTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearUnixTimeList = function() {
  return this.setUnixTimeList([]);
};


/**
 * repeated float latitude = 2;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getLatitudeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 2));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setLatitudeList = function(value) {
  return jspb.Message.setField(this, 2, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addLatitude = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 2, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearLatitudeList = function() {
  return this.setLatitudeList([]);
};


/**
 * repeated float longitude = 3;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getLongitudeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 3));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setLongitudeList = function(value) {
  return jspb.Message.setField(this, 3, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addLongitude = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 3, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearLongitudeList = function() {
  return this.setLongitudeList([]);
};


/**
 * repeated float heading = 4;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getHeadingList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 4));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setHeadingList = function(value) {
  return jspb.Message.setField(this, 4, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addHeading = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 4, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearHeadingList = function() {
  return this.setHeadingList([]);
};


/**
 * repeated float prop_pitch = 5;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getPropPitchList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 5));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setPropPitchList = function(value) {
  return jspb.Message.setField(this, 5, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addPropPitch = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 5, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearPropPitchList = function() {
  return this.setPropPitchList([]);
};


/**
 * repeated float motor_speed = 6;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getMotorSpeedList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 6));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setMotorSpeedList = function(value) {
  return jspb.Message.setField(this, 6, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addMotorSpeed = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 6, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearMotorSpeedList = function() {
  return this.setMotorSpeedList([]);
};


/**
 * repeated float SOG = 7;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.getSogList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 7));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.setSogList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.addSog = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisRequest} returns this
 */
proto.webGateway.v1.RouteAnalysisRequest.prototype.clearSogList = function() {
  return this.setSogList([]);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.webGateway.v1.RouteAnalysisResponse.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.toObject = function(opt_includeInstance) {
  return proto.webGateway.v1.RouteAnalysisResponse.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.webGateway.v1.RouteAnalysisResponse} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.RouteAnalysisResponse.toObject = function(includeInstance, msg) {
  var f, obj = {
    unixTimeList: (f = jspb.Message.getRepeatedFloatingPointField(msg, 1)) == null ? undefined : f,
    averagePower: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    totalCost: jspb.Message.getFloatingPointFieldWithDefault(msg, 3, 0.0),
    averageRmsX: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0),
    averageRmsY: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0),
    averageRmsZ: jspb.Message.getFloatingPointFieldWithDefault(msg, 6, 0.0),
    comfortLevel: jspb.Message.getFieldWithDefault(msg, 7, 0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.webGateway.v1.RouteAnalysisResponse}
 */
proto.webGateway.v1.RouteAnalysisResponse.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.webGateway.v1.RouteAnalysisResponse;
  return proto.webGateway.v1.RouteAnalysisResponse.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.webGateway.v1.RouteAnalysisResponse} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.webGateway.v1.RouteAnalysisResponse}
 */
proto.webGateway.v1.RouteAnalysisResponse.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var values = /** @type {!Array<number>} */ (reader.isDelimited() ? reader.readPackedDouble() : [reader.readDouble()]);
      for (var i = 0; i < values.length; i++) {
        msg.addUnixTime(values[i]);
      }
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setAveragePower(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setTotalCost(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAverageRmsX(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAverageRmsY(value);
      break;
    case 6:
      var value = /** @type {number} */ (reader.readDouble());
      msg.setAverageRmsZ(value);
      break;
    case 7:
      var value = /** @type {!proto.webGateway.v1.HabitibilityRating} */ (reader.readEnum());
      msg.setComfortLevel(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.webGateway.v1.RouteAnalysisResponse.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.webGateway.v1.RouteAnalysisResponse} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.webGateway.v1.RouteAnalysisResponse.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUnixTimeList();
  if (f.length > 0) {
    writer.writePackedDouble(
      1,
      f
    );
  }
  f = message.getAveragePower();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getTotalCost();
  if (f !== 0.0) {
    writer.writeFloat(
      3,
      f
    );
  }
  f = message.getAverageRmsX();
  if (f !== 0.0) {
    writer.writeDouble(
      4,
      f
    );
  }
  f = message.getAverageRmsY();
  if (f !== 0.0) {
    writer.writeDouble(
      5,
      f
    );
  }
  f = message.getAverageRmsZ();
  if (f !== 0.0) {
    writer.writeDouble(
      6,
      f
    );
  }
  f = message.getComfortLevel();
  if (f !== 0.0) {
    writer.writeEnum(
      7,
      f
    );
  }
};


/**
 * repeated double unix_time = 1;
 * @return {!Array<number>}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getUnixTimeList = function() {
  return /** @type {!Array<number>} */ (jspb.Message.getRepeatedFloatingPointField(this, 1));
};


/**
 * @param {!Array<number>} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setUnixTimeList = function(value) {
  return jspb.Message.setField(this, 1, value || []);
};


/**
 * @param {number} value
 * @param {number=} opt_index
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.addUnixTime = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 1, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.clearUnixTimeList = function() {
  return this.setUnixTimeList([]);
};


/**
 * optional float average_power = 2;
 * @return {number}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getAveragePower = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setAveragePower = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional float total_cost = 3;
 * @return {number}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getTotalCost = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 3, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setTotalCost = function(value) {
  return jspb.Message.setProto3FloatField(this, 3, value);
};


/**
 * optional double average_rms_x = 4;
 * @return {number}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getAverageRmsX = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setAverageRmsX = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


/**
 * optional double average_rms_y = 5;
 * @return {number}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getAverageRmsY = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setAverageRmsY = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};


/**
 * optional double average_rms_z = 6;
 * @return {number}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getAverageRmsZ = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 6, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setAverageRmsZ = function(value) {
  return jspb.Message.setProto3FloatField(this, 6, value);
};


/**
 * optional HabitibilityRating comfort_level = 7;
 * @return {!proto.webGateway.v1.HabitibilityRating}
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.getComfortLevel = function() {
  return /** @type {!proto.webGateway.v1.HabitibilityRating} */ (jspb.Message.getFieldWithDefault(this, 7, 0));
};


/**
 * @param {!proto.webGateway.v1.HabitibilityRating} value
 * @return {!proto.webGateway.v1.RouteAnalysisResponse} returns this
 */
proto.webGateway.v1.RouteAnalysisResponse.prototype.setComfortLevel = function(value) {
  return jspb.Message.setProto3EnumField(this, 7, value);
};


/**
 * @enum {number}
 */
proto.webGateway.v1.HabitibilityRating = {
  UNKNOWN_RATING: 0,
  NOT_UNCOMFORTABLE: 1,
  SLIGHTLY_UNCOMFORTABLE: 2,
  FAIRLY_UNCOMFORTABLE: 3,
  UNCOMFORTABLE: 4,
  VERY_UNCOMFORTABLE: 5,
  EXTREMELY_UNCOMFORTABLE: 6
};

goog.object.extend(exports, proto.webGateway.v1);
