# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: propeller_monitor_service_api_v1.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='propeller_monitor_service_api_v1.proto',
  package='propellerMonitorService.v1',
  syntax='proto3',
  serialized_options=b'Z2propellerMonitorService/v1;propellerMonitorService',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n&propeller_monitor_service_api_v1.proto\x12\x1apropellerMonitorService.v1\"\x16\n\x14PropellerLoadRequest\"l\n\x15PropellerLoadResponse\x12\x11\n\tunix_time\x18\x01 \x03(\x01\x12\x10\n\x08ice_load\x18\x02 \x03(\x01\x12\x14\n\x0cmotor_torque\x18\x03 \x03(\x01\x12\x18\n\x10propeller_torque\x18\x04 \x03(\x01\x32\x99\x01\n\x17MonitorPropellerService\x12~\n\x15\x45stimatePropellerLoad\x12\x30.propellerMonitorService.v1.PropellerLoadRequest\x1a\x31.propellerMonitorService.v1.PropellerLoadResponse0\x01\x42\x34Z2propellerMonitorService/v1;propellerMonitorServiceb\x06proto3'
)




_PROPELLERLOADREQUEST = _descriptor.Descriptor(
  name='PropellerLoadRequest',
  full_name='propellerMonitorService.v1.PropellerLoadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=92,
)


_PROPELLERLOADRESPONSE = _descriptor.Descriptor(
  name='PropellerLoadResponse',
  full_name='propellerMonitorService.v1.PropellerLoadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='unix_time', full_name='propellerMonitorService.v1.PropellerLoadResponse.unix_time', index=0,
      number=1, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ice_load', full_name='propellerMonitorService.v1.PropellerLoadResponse.ice_load', index=1,
      number=2, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motor_torque', full_name='propellerMonitorService.v1.PropellerLoadResponse.motor_torque', index=2,
      number=3, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='propeller_torque', full_name='propellerMonitorService.v1.PropellerLoadResponse.propeller_torque', index=3,
      number=4, type=1, cpp_type=5, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=94,
  serialized_end=202,
)

DESCRIPTOR.message_types_by_name['PropellerLoadRequest'] = _PROPELLERLOADREQUEST
DESCRIPTOR.message_types_by_name['PropellerLoadResponse'] = _PROPELLERLOADRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PropellerLoadRequest = _reflection.GeneratedProtocolMessageType('PropellerLoadRequest', (_message.Message,), {
  'DESCRIPTOR' : _PROPELLERLOADREQUEST,
  '__module__' : 'propeller_monitor_service_api_v1_pb2'
  # @@protoc_insertion_point(class_scope:propellerMonitorService.v1.PropellerLoadRequest)
  })
_sym_db.RegisterMessage(PropellerLoadRequest)

PropellerLoadResponse = _reflection.GeneratedProtocolMessageType('PropellerLoadResponse', (_message.Message,), {
  'DESCRIPTOR' : _PROPELLERLOADRESPONSE,
  '__module__' : 'propeller_monitor_service_api_v1_pb2'
  # @@protoc_insertion_point(class_scope:propellerMonitorService.v1.PropellerLoadResponse)
  })
_sym_db.RegisterMessage(PropellerLoadResponse)


DESCRIPTOR._options = None

_MONITORPROPELLERSERVICE = _descriptor.ServiceDescriptor(
  name='MonitorPropellerService',
  full_name='propellerMonitorService.v1.MonitorPropellerService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=205,
  serialized_end=358,
  methods=[
  _descriptor.MethodDescriptor(
    name='EstimatePropellerLoad',
    full_name='propellerMonitorService.v1.MonitorPropellerService.EstimatePropellerLoad',
    index=0,
    containing_service=None,
    input_type=_PROPELLERLOADREQUEST,
    output_type=_PROPELLERLOADRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_MONITORPROPELLERSERVICE)

DESCRIPTOR.services_by_name['MonitorPropellerService'] = _MONITORPROPELLERSERVICE

# @@protoc_insertion_point(module_scope)
